- name: Check connectivity to remote servers
  become: yes
  become_user: ahmed
  hosts: all
  tasks:
    - name: ping
      ping:
      
    - name: just a simple text
      debug:
        msg: "C'est moi, je sais daire des passes!"
